backend:
  name: "github"
  repo: "DevinOLeary/Inkwell"

media_folder: "src/assets"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    fields:
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "drink_menu"
    label: "Drink Type"
    folder: "drink_menus"
    create: true
    fields:
      - {
        label: "Drink Type",
        name: "title",
        widget: "string"
        }
      - {
        label: "Optional Group Cost",
        name: "group_cost",
        widget: "number",
        required: false
        }
      - label: "Drink Item"
        name: "drink_item"
        widget: "list"
        fields:
          - {label: Name, name: item_name, widget: string}
          - {label: Cost, name: item_cost, widget: number}
          - {label: Image, name: item_image, widget: image}

  - name: "food_menu"
    label: "Food Type"
    folder: "food_menus"
    create: true
    fields:
      - {
        label: "Food Type",
        name: "title",
        widget: "string"
        }
      - {
        label: "Optional Group Cost",
        name: "group_cost",
        widget: "number",
        required: false
        }
      - label: "Food Item"
        name: "food_item"
        widget: "list"
        fields:
          - {label: Name, name: item_name, widget: string}
          - {label: Cost, name: item_cost, widget: number}
          - {label: Image, name: item_image, widget: image}
  - label: "Merch"
    name: "merch"
    folder: "merch"
    create: true
    fields:
      - {label: "Item Name", name: "merch_item_name", widget: "string"}
      - {label: "Item Cost", name: "merch_item-cost", widget: "number"}
      - {label: "Description", name: "merch_item_description", widget: "text", required: false}
      - {label: "Item Image", name: "merch_item_image", widget: "image"}
